sudo: required
language: php
dist: trusty

# Keep the cache between builds to speed up installs
cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.4

install:
    - cp .env-example .env
    - travis_retry composer install --no-interaction --prefer-dist --no-suggest
    - php artisan key:generate --ansi

script:
    - vendor/bin/phpunit
