language: php

# Keep the cache between builds to speed up installs
cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.4

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

install:
    - cp .env-example .env
    - travis_retry composer install --no-interaction --prefer-dist --no-suggest
    - php artisan key:generate --ansi

script:
    - vendor/bin/phpcs
    - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
