# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.registry.URL_HUB }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build and push images
        run: |
          docker build -t ${{ env.registry.BASE_IMAGE_TAG_HUB }}:${{ github.sha }} .
          docker push ${{ env.registry.BASE_IMAGE_TAG_HUB }}:${{ github.sha }}
          echo "::set-output name=image::${{ env.registry.BASE_IMAGE_TAG_HUB }}:${{ github.sha }}"
      - name: Deploy to caprover
        uses: floms/action-caprover@v1
        with:
          host: ${{ secrets.CAPROVER_SERVER }}
          password: ${{ secrets.CAPROVER_PASSWORD }}
          app: ${{ secrets.CAPROVER_APPNAMEDEV }}
          image: ${{ env.registry.BASE_IMAGE_TAG_HUB }}:${{ github.sha }}
