# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2
      
      - name: Setup .env
        run: php -r "file_exists('.env') || copy('.env-example', '.env');"
      
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
      - name: Generate Key!
        run: php artisan key:generate
        
      - name: Give a dir permissions
        run: chmod -R 777 storage bootstrap/cache
        
      - name: Create a Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      
      - name: Running a PHPCS
        run: vendor/bin/phpcs
        
      - name: Running a Testing
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
